# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: informationBlueprint_v1.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='informationBlueprint_v1.proto',
  package='portraits',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1dinformationBlueprint_v1.proto\x12\tportraits\"\xcd\x04\n\x0bInformation\x12\x17\n\x0finformationName\x18\x01 \x01(\t\x12\x1b\n\x13informationCategory\x18\x02 \x03(\t\x12\x34\n\nprocessors\x18\x03 \x03(\x0b\x32 .portraits.Information.Processor\x1a\xd1\x03\n\tProcessor\x12U\n\x14\x64ownloadZipImageFile\x18\x01 \x01(\x0b\x32\x35.portraits.Information.Processor.DownloadZipImageFileH\x00\x12\x37\n\x05mnist\x18\x02 \x01(\x0b\x32&.portraits.Information.Processor.MNISTH\x00\x12\x61\n\x1a\x65xtractImageFromImageArray\x18\x03 \x01(\x0b\x32;.portraits.Information.Processor.ExtractImageFromImageArrayH\x01\x1a\x42\n\x14\x44ownloadZipImageFile\x12\x13\n\x0b\x64ownloadURL\x18\x01 \x01(\t\x12\x15\n\rdirectoryName\x18\x02 \x01(\t\x1a\x41\n\x05MNIST\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\x12\x10\n\x08\x64\x61taType\x18\x02 \x01(\t\x12\x14\n\x0c\x64\x61taProvider\x18\x03 \x01(\t\x1a\x33\n\x1a\x45xtractImageFromImageArray\x12\x15\n\rextractorName\x18\x01 \x01(\tB\x08\n\x06LoaderB\x0b\n\tExtractorb\x06proto3')
)




_INFORMATION_PROCESSOR_DOWNLOADZIPIMAGEFILE = _descriptor.Descriptor(
  name='DownloadZipImageFile',
  full_name='portraits.Information.Processor.DownloadZipImageFile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='downloadURL', full_name='portraits.Information.Processor.DownloadZipImageFile.downloadURL', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='directoryName', full_name='portraits.Information.Processor.DownloadZipImageFile.directoryName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=425,
  serialized_end=491,
)

_INFORMATION_PROCESSOR_MNIST = _descriptor.Descriptor(
  name='MNIST',
  full_name='portraits.Information.Processor.MNIST',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='category', full_name='portraits.Information.Processor.MNIST.category', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dataType', full_name='portraits.Information.Processor.MNIST.dataType', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dataProvider', full_name='portraits.Information.Processor.MNIST.dataProvider', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=493,
  serialized_end=558,
)

_INFORMATION_PROCESSOR_EXTRACTIMAGEFROMIMAGEARRAY = _descriptor.Descriptor(
  name='ExtractImageFromImageArray',
  full_name='portraits.Information.Processor.ExtractImageFromImageArray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='extractorName', full_name='portraits.Information.Processor.ExtractImageFromImageArray.extractorName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=560,
  serialized_end=611,
)

_INFORMATION_PROCESSOR = _descriptor.Descriptor(
  name='Processor',
  full_name='portraits.Information.Processor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='downloadZipImageFile', full_name='portraits.Information.Processor.downloadZipImageFile', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mnist', full_name='portraits.Information.Processor.mnist', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='extractImageFromImageArray', full_name='portraits.Information.Processor.extractImageFromImageArray', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_INFORMATION_PROCESSOR_DOWNLOADZIPIMAGEFILE, _INFORMATION_PROCESSOR_MNIST, _INFORMATION_PROCESSOR_EXTRACTIMAGEFROMIMAGEARRAY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='Loader', full_name='portraits.Information.Processor.Loader',
      index=0, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='Extractor', full_name='portraits.Information.Processor.Extractor',
      index=1, containing_type=None, fields=[]),
  ],
  serialized_start=169,
  serialized_end=634,
)

_INFORMATION = _descriptor.Descriptor(
  name='Information',
  full_name='portraits.Information',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='informationName', full_name='portraits.Information.informationName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='informationCategory', full_name='portraits.Information.informationCategory', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='processors', full_name='portraits.Information.processors', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_INFORMATION_PROCESSOR, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=634,
)

_INFORMATION_PROCESSOR_DOWNLOADZIPIMAGEFILE.containing_type = _INFORMATION_PROCESSOR
_INFORMATION_PROCESSOR_MNIST.containing_type = _INFORMATION_PROCESSOR
_INFORMATION_PROCESSOR_EXTRACTIMAGEFROMIMAGEARRAY.containing_type = _INFORMATION_PROCESSOR
_INFORMATION_PROCESSOR.fields_by_name['downloadZipImageFile'].message_type = _INFORMATION_PROCESSOR_DOWNLOADZIPIMAGEFILE
_INFORMATION_PROCESSOR.fields_by_name['mnist'].message_type = _INFORMATION_PROCESSOR_MNIST
_INFORMATION_PROCESSOR.fields_by_name['extractImageFromImageArray'].message_type = _INFORMATION_PROCESSOR_EXTRACTIMAGEFROMIMAGEARRAY
_INFORMATION_PROCESSOR.containing_type = _INFORMATION
_INFORMATION_PROCESSOR.oneofs_by_name['Loader'].fields.append(
  _INFORMATION_PROCESSOR.fields_by_name['downloadZipImageFile'])
_INFORMATION_PROCESSOR.fields_by_name['downloadZipImageFile'].containing_oneof = _INFORMATION_PROCESSOR.oneofs_by_name['Loader']
_INFORMATION_PROCESSOR.oneofs_by_name['Loader'].fields.append(
  _INFORMATION_PROCESSOR.fields_by_name['mnist'])
_INFORMATION_PROCESSOR.fields_by_name['mnist'].containing_oneof = _INFORMATION_PROCESSOR.oneofs_by_name['Loader']
_INFORMATION_PROCESSOR.oneofs_by_name['Extractor'].fields.append(
  _INFORMATION_PROCESSOR.fields_by_name['extractImageFromImageArray'])
_INFORMATION_PROCESSOR.fields_by_name['extractImageFromImageArray'].containing_oneof = _INFORMATION_PROCESSOR.oneofs_by_name['Extractor']
_INFORMATION.fields_by_name['processors'].message_type = _INFORMATION_PROCESSOR
DESCRIPTOR.message_types_by_name['Information'] = _INFORMATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Information = _reflection.GeneratedProtocolMessageType('Information', (_message.Message,), dict(

  Processor = _reflection.GeneratedProtocolMessageType('Processor', (_message.Message,), dict(

    DownloadZipImageFile = _reflection.GeneratedProtocolMessageType('DownloadZipImageFile', (_message.Message,), dict(
      DESCRIPTOR = _INFORMATION_PROCESSOR_DOWNLOADZIPIMAGEFILE,
      __module__ = 'informationBlueprint_v1_pb2'
      # @@protoc_insertion_point(class_scope:portraits.Information.Processor.DownloadZipImageFile)
      ))
    ,

    MNIST = _reflection.GeneratedProtocolMessageType('MNIST', (_message.Message,), dict(
      DESCRIPTOR = _INFORMATION_PROCESSOR_MNIST,
      __module__ = 'informationBlueprint_v1_pb2'
      # @@protoc_insertion_point(class_scope:portraits.Information.Processor.MNIST)
      ))
    ,

    ExtractImageFromImageArray = _reflection.GeneratedProtocolMessageType('ExtractImageFromImageArray', (_message.Message,), dict(
      DESCRIPTOR = _INFORMATION_PROCESSOR_EXTRACTIMAGEFROMIMAGEARRAY,
      __module__ = 'informationBlueprint_v1_pb2'
      # @@protoc_insertion_point(class_scope:portraits.Information.Processor.ExtractImageFromImageArray)
      ))
    ,
    DESCRIPTOR = _INFORMATION_PROCESSOR,
    __module__ = 'informationBlueprint_v1_pb2'
    # @@protoc_insertion_point(class_scope:portraits.Information.Processor)
    ))
  ,
  DESCRIPTOR = _INFORMATION,
  __module__ = 'informationBlueprint_v1_pb2'
  # @@protoc_insertion_point(class_scope:portraits.Information)
  ))
_sym_db.RegisterMessage(Information)
_sym_db.RegisterMessage(Information.Processor)
_sym_db.RegisterMessage(Information.Processor.DownloadZipImageFile)
_sym_db.RegisterMessage(Information.Processor.MNIST)
_sym_db.RegisterMessage(Information.Processor.ExtractImageFromImageArray)


# @@protoc_insertion_point(module_scope)
