# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Khandhasamy.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Khandhasamy.proto',
  package='Family.Khandhasamy',
  syntax='proto3',
  serialized_pb=_b('\n\x11Khandhasamy.proto\x12\x12\x46\x61mily.Khandhasamy\"\x97\x07\n\x03\x44NA\x12\x0b\n\x03\x44NA\x18\x01 \x01(\t\x12-\n\x06inputs\x18\x02 \x03(\x0b\x32\x1d.Family.Khandhasamy.DNA.Input\x12-\n\x06layers\x18\x03 \x03(\x0b\x32\x1d.Family.Khandhasamy.DNA.Layer\x12/\n\x07outputs\x18\x04 \x03(\x0b\x32\x1e.Family.Khandhasamy.DNA.Output\x12\x37\n\x0b\x63onnections\x18\x05 \x03(\x0b\x32\".Family.Khandhasamy.DNA.Connection\x1a\xbe\x01\n\x05Input\x12\x16\n\x0einputLayerName\x18\x01 \x01(\t\x12\x11\n\tinputSize\x18\x02 \x01(\x04\x12\x39\n\x0einputTransform\x18\x03 \x01(\x0b\x32!.Family.Khandhasamy.DNA.Transform\x12\x16\n\x0einputLayerType\x18\x04 \x01(\t\x12\x37\n\x0b\x63onnections\x18\x05 \x03(\x0b\x32\".Family.Khandhasamy.DNA.Connection\x1ay\n\x05Layer\x12\x11\n\tlayerName\x18\x01 \x01(\t\x12\x11\n\tlayerType\x18\x02 \x01(\t\x12\x11\n\tlayerSize\x18\x03 \x01(\t\x12\x37\n\x0b\x63onnections\x18\x04 \x03(\x0b\x32\".Family.Khandhasamy.DNA.Connection\x1a\xaf\x01\n\x06Output\x12\x17\n\x0foutputLayerName\x18\x01 \x01(\t\x12\x17\n\x0foutputLayerType\x18\x02 \x01(\t\x12:\n\x0foutputTransform\x18\x03 \x01(\x0b\x32!.Family.Khandhasamy.DNA.Transform\x12\x37\n\x0b\x63onnections\x18\x04 \x03(\x0b\x32\".Family.Khandhasamy.DNA.Connection\x1a\x86\x01\n\tTransform\x12\x17\n\x0ftransformerName\x18\x01 \x01(\t\x12\x17\n\x0finformationType\x18\x02 \x01(\t\x12\x17\n\x0ftransformHeight\x18\x03 \x01(\x04\x12\x16\n\x0etransformWidth\x18\x04 \x01(\x04\x12\x16\n\x0etransformParam\x18\x05 \x01(\t\x1a\x44\n\nConnection\x12\x17\n\x0fsourceLayerName\x18\x01 \x01(\t\x12\x1d\n\x15\x64\x65stionationLayerName\x18\x02 \x01(\tb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DNA_INPUT = _descriptor.Descriptor(
  name='Input',
  full_name='Family.Khandhasamy.DNA.Input',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='inputLayerName', full_name='Family.Khandhasamy.DNA.Input.inputLayerName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='inputSize', full_name='Family.Khandhasamy.DNA.Input.inputSize', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='inputTransform', full_name='Family.Khandhasamy.DNA.Input.inputTransform', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='inputLayerType', full_name='Family.Khandhasamy.DNA.Input.inputLayerType', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='connections', full_name='Family.Khandhasamy.DNA.Input.connections', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=453,
)

_DNA_LAYER = _descriptor.Descriptor(
  name='Layer',
  full_name='Family.Khandhasamy.DNA.Layer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='layerName', full_name='Family.Khandhasamy.DNA.Layer.layerName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='layerType', full_name='Family.Khandhasamy.DNA.Layer.layerType', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='layerSize', full_name='Family.Khandhasamy.DNA.Layer.layerSize', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='connections', full_name='Family.Khandhasamy.DNA.Layer.connections', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=455,
  serialized_end=576,
)

_DNA_OUTPUT = _descriptor.Descriptor(
  name='Output',
  full_name='Family.Khandhasamy.DNA.Output',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='outputLayerName', full_name='Family.Khandhasamy.DNA.Output.outputLayerName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='outputLayerType', full_name='Family.Khandhasamy.DNA.Output.outputLayerType', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='outputTransform', full_name='Family.Khandhasamy.DNA.Output.outputTransform', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='connections', full_name='Family.Khandhasamy.DNA.Output.connections', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=579,
  serialized_end=754,
)

_DNA_TRANSFORM = _descriptor.Descriptor(
  name='Transform',
  full_name='Family.Khandhasamy.DNA.Transform',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='transformerName', full_name='Family.Khandhasamy.DNA.Transform.transformerName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='informationType', full_name='Family.Khandhasamy.DNA.Transform.informationType', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='transformHeight', full_name='Family.Khandhasamy.DNA.Transform.transformHeight', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='transformWidth', full_name='Family.Khandhasamy.DNA.Transform.transformWidth', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='transformParam', full_name='Family.Khandhasamy.DNA.Transform.transformParam', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=757,
  serialized_end=891,
)

_DNA_CONNECTION = _descriptor.Descriptor(
  name='Connection',
  full_name='Family.Khandhasamy.DNA.Connection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sourceLayerName', full_name='Family.Khandhasamy.DNA.Connection.sourceLayerName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='destionationLayerName', full_name='Family.Khandhasamy.DNA.Connection.destionationLayerName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=893,
  serialized_end=961,
)

_DNA = _descriptor.Descriptor(
  name='DNA',
  full_name='Family.Khandhasamy.DNA',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='DNA', full_name='Family.Khandhasamy.DNA.DNA', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='inputs', full_name='Family.Khandhasamy.DNA.inputs', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='layers', full_name='Family.Khandhasamy.DNA.layers', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='outputs', full_name='Family.Khandhasamy.DNA.outputs', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='connections', full_name='Family.Khandhasamy.DNA.connections', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_DNA_INPUT, _DNA_LAYER, _DNA_OUTPUT, _DNA_TRANSFORM, _DNA_CONNECTION, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=961,
)

_DNA_INPUT.fields_by_name['inputTransform'].message_type = _DNA_TRANSFORM
_DNA_INPUT.fields_by_name['connections'].message_type = _DNA_CONNECTION
_DNA_INPUT.containing_type = _DNA
_DNA_LAYER.fields_by_name['connections'].message_type = _DNA_CONNECTION
_DNA_LAYER.containing_type = _DNA
_DNA_OUTPUT.fields_by_name['outputTransform'].message_type = _DNA_TRANSFORM
_DNA_OUTPUT.fields_by_name['connections'].message_type = _DNA_CONNECTION
_DNA_OUTPUT.containing_type = _DNA
_DNA_TRANSFORM.containing_type = _DNA
_DNA_CONNECTION.containing_type = _DNA
_DNA.fields_by_name['inputs'].message_type = _DNA_INPUT
_DNA.fields_by_name['layers'].message_type = _DNA_LAYER
_DNA.fields_by_name['outputs'].message_type = _DNA_OUTPUT
_DNA.fields_by_name['connections'].message_type = _DNA_CONNECTION
DESCRIPTOR.message_types_by_name['DNA'] = _DNA

DNA = _reflection.GeneratedProtocolMessageType('DNA', (_message.Message,), dict(

  Input = _reflection.GeneratedProtocolMessageType('Input', (_message.Message,), dict(
    DESCRIPTOR = _DNA_INPUT,
    __module__ = 'Khandhasamy_pb2'
    # @@protoc_insertion_point(class_scope:Family.Khandhasamy.DNA.Input)
    ))
  ,

  Layer = _reflection.GeneratedProtocolMessageType('Layer', (_message.Message,), dict(
    DESCRIPTOR = _DNA_LAYER,
    __module__ = 'Khandhasamy_pb2'
    # @@protoc_insertion_point(class_scope:Family.Khandhasamy.DNA.Layer)
    ))
  ,

  Output = _reflection.GeneratedProtocolMessageType('Output', (_message.Message,), dict(
    DESCRIPTOR = _DNA_OUTPUT,
    __module__ = 'Khandhasamy_pb2'
    # @@protoc_insertion_point(class_scope:Family.Khandhasamy.DNA.Output)
    ))
  ,

  Transform = _reflection.GeneratedProtocolMessageType('Transform', (_message.Message,), dict(
    DESCRIPTOR = _DNA_TRANSFORM,
    __module__ = 'Khandhasamy_pb2'
    # @@protoc_insertion_point(class_scope:Family.Khandhasamy.DNA.Transform)
    ))
  ,

  Connection = _reflection.GeneratedProtocolMessageType('Connection', (_message.Message,), dict(
    DESCRIPTOR = _DNA_CONNECTION,
    __module__ = 'Khandhasamy_pb2'
    # @@protoc_insertion_point(class_scope:Family.Khandhasamy.DNA.Connection)
    ))
  ,
  DESCRIPTOR = _DNA,
  __module__ = 'Khandhasamy_pb2'
  # @@protoc_insertion_point(class_scope:Family.Khandhasamy.DNA)
  ))
_sym_db.RegisterMessage(DNA)
_sym_db.RegisterMessage(DNA.Input)
_sym_db.RegisterMessage(DNA.Layer)
_sym_db.RegisterMessage(DNA.Output)
_sym_db.RegisterMessage(DNA.Transform)
_sym_db.RegisterMessage(DNA.Connection)


# @@protoc_insertion_point(module_scope)
